### ISSUE TITLE
support hash calculation of hexadecimal numbers

### ISSUE THREAD

**Issue by ifreecoding** [ilvn/SHA256#7]
You can remove the judgment that the data is NULL so that you can support hash calculation of hexadecimal numbers.
Make the following modifications in the sha256_hash function:
if ((ctx != NULL) && /* (bytes != NULL) && */ (ctx->len < sizeof(ctx->buf))) {

**Comment by ilvn** [comment]
It is not entirely clear what is an actual suggestion here; still, it doesn't sound like an issue that needs a fix.

**Comment by ifreecoding** [comment]
If I want to calculate a hexadecimal number, the hexadecimal number may contain 0, which is NULL. Then the judgment of "(bytes != NULL)" will abnormally exit the process of calculating 0.

**Comment by ilvn** [comment]
This is not how it works. Still, feel free to fork and modify whatever you think you need.
